name: "Analyze"
on:
  workflow_dispatch:

jobs:
  Analyze:
    runs-on: eclairit-1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: tonasodji/hello-world
