name: "Analyze"
on:
  workflow_dispatch:
env:
  PROJECT_PATH: "tools/${GITHUB_REPOSITORY}"
  RELEASE_BRANCH: "main"
  ECD_DIR: "/home/emelin/github/${GITHUB_REPOSITORY}/${GITHUB_RUN_NUMBER}"
  ECD_FILE: "${ECD_DIR}/PROJECT.ecd"
  LAST_ECD_DIR: "/home/emelin/github/$GITHUB_REPOSITORY/last_$GITHUB_REF_NAME"

jobs:
  Analyze:
    runs-on: eclairit-1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Analyze
      run: |
        git clone -b "${RELEASE_BRANCH}" --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:8444/${PROJECT_PATH}.git .gitlab
      # Prepare for build
        .gitlab/prepare.sh
    # Analyze the project
        .gitlab/analyze.sh openssh
    # Make the directory for the ECLAIR project database
        ssh eclair-gitlab@localhost "mkdir -p ${ECD_DIR} && rm -f ${LAST_ECD_DIR} && ln -s ${ECD_DIR} ${LAST_ECD_DIR}"
    # Copy the project database
        scp ECLAIR/out/PROJECT.ecd eclair-gitlab@localhost:${ECD_FILE}
    # Publish the ECLAIR report link
        echo "https://eclairit.com:3787/fs/home/eclair-gitlab/gitlab/$CI_PROJECT_PATH/$CI_JOB_ID/PROJECT.ecd"
    # Create the ECLAIR badge
        anybadge --label=ECLAIR --value=default --file=ECLAIR/badge.svg
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR/out


    - name: reports SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ECLAIR/gh-quality-report.sarif
